### ISSUE TITLE
Lower timeout to 5-10 seconds

### ISSUE THREAD

**Issue by brendanlong** [cablelabs/QtRUIBrowser#5]
Eric requested this a while ago. I think it can be done with a timer.

**Comment by svenyonson** [comment]
If this is about ensuring that the UI gets refreshed when a RUIServer goes away, this should be working correctly now. There was a bug in the Discovery module (webkit) that was not deleting devices that did not respond and so didn't notify the client (QtRUIBrowser). We currently check for dropped devices every 5 seconds (UPnPSearch.cpp:84)

**Comment by brendanlong** [comment]
I think Eric just wants to the timeout if a page doesn't exist to be lower, since it's hard to test that since it takes so long for page loading to time out.

**Comment by brendanlong** [comment]
@ewinkelman Can you clarify where you were having this long timeout problem?

**Comment by brendanlong** [comment]
So here's a testcase:
- Run ruiserver. Make sure whatever it points to doesn't exist.
- Start QtRUIBrowser.
- Click the Path_Test link.

It seems to take around a minute to timeout, and doesn't display any notification that it failed.
